version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    # 開放容器 3306 在本地連線
    ports:
      - 3306:3306
    # 持久化資料庫，服務重啟後仍存在
    volumes:
      - mysql-data-volume:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.rule=Host(`adminer.website`)
      - traefik.http.routers.adminer-https.tls=false

  apple:
    image: joomla:3.10.8
    container_name: apple
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_PASSWORD: root
      JOOMLA_DB_NAME: apple
    labels:
      - traefik.enable=true
      # 啟用 HTTP
      - traefik.http.routers.apple.rule=Host(`apple.website`)
      # 啟用 HTTPS
      - traefik.http.routers.apple-https.entrypoints=websecure
      - traefik.http.routers.apple-https.tls=true
      - traefik.http.routers.apple-https.rule=Host(`apple.website`)
    restart: unless-stopped
    volumes:
      # 設定本地掛載目錄，可直接修改容器內網站內容
      # - ./apple:/var/www/html
      # PHP 設定檔
      - ./php/etc/php.ini:/usr/local/etc/php/php.ini:ro
  google:
    image: joomla:3.10.8
    container_name: google
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_PASSWORD: root
      JOOMLA_DB_NAME: google
    labels:
      - traefik.enable=true
      # 啟用 HTTP
      - traefik.http.routers.google.rule=Host(`google.website`)
      # 啟用 HTTPS
      - traefik.http.routers.google-https.entrypoints=websecure
      - traefik.http.routers.google-https.tls=true
      - traefik.http.routers.google-https.rule=Host(`google.website`)
    restart: unless-stopped
    volumes:
      # 設定本地掛載目錄，可直接修改容器內網站內容
      # - ./google:/var/www/html
      # PHP 設定檔
      - ./php/etc/php.ini:/usr/local/etc/php/php.ini:ro

  traefik:
    image: traefik
    container_name: traefik
    command:
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic/
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/etc:/etc/traefik:ro

volumes:
  mysql-data-volume: